server:
  port: 5000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: Boynextdoor123
    url: jdbc:mysql://blog.cx4tqduywofq.us-east-1.rds.amazonaws.com:3306/application_submission?useAffectedRows=true


mybatis:
  mapper-locations: classpath:mappers/*.xml
  config-location: classpath:mybatis.xml

